apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypythonflaskapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mypythonflaskapp
  template:
    metadata:
      labels:
        app: mypythonflaskapp
    spec:
      containers:
        - name: mypythonflaskapp
          image: swathi1276/week8:latest
          ports:
            - containerPort: 5000
